repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        name: python-types
        entry: bash -c 'stubgen packages/python/accern_xyme/accern_xyme.py -o packages/types'
