# Stubs for pandas.io.formats.console (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def get_console_size():
    ...


def in_interactive_session():
    ...


def in_ipython_frontend():
    ...
