from typing import Any
# Stubs for pandas._config.display (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.


def detect_console_encoding() -> Any:
    ...


pc_encoding_doc: str
