import io
import pandas as pd
from .types import AllowedCustomImports as AllowedCustomImports, BlobDetails as BlobDetails, BlobFilesResponse as BlobFilesResponse, BlobInit as BlobInit, BlobOwner as BlobOwner, BlobTypeResponse as BlobTypeResponse, BlobURIResponse as BlobURIResponse, CacheStats as CacheStats, CopyBlob as CopyBlob, DagCreate as DagCreate, DagDupResponse as DagDupResponse, DagInfo as DagInfo, DagInit as DagInit, DagList as DagList, DagPrettyNode as DagPrettyNode, DagReload as DagReload, DagStatus as DagStatus, DeleteBlobResponse as DeleteBlobResponse, DynamicResults as DynamicResults, DynamicStatusResponse as DynamicStatusResponse, ESQueryResponse as ESQueryResponse, FileMap as FileMap, FlushAllQueuesResponse as FlushAllQueuesResponse, InCursors as InCursors, InstanceStatus as InstanceStatus, JSONBlobAppendResponse as JSONBlobAppendResponse, KafkaGroup as KafkaGroup, KafkaMessage as KafkaMessage, KafkaOffsets as KafkaOffsets, KafkaThroughput as KafkaThroughput, KafkaTopicNames as KafkaTopicNames, KafkaTopics as KafkaTopics, KnownBlobs as KnownBlobs, MinimalQueueStatsResponse as MinimalQueueStatsResponse, ModelInfo as ModelInfo, ModelParamsResponse as ModelParamsResponse, ModelReleaseResponse as ModelReleaseResponse, ModelVersionResponse as ModelVersionResponse, NamespaceList as NamespaceList, NamespaceUpdateSettings as NamespaceUpdateSettings, NodeChunk as NodeChunk, NodeCustomCode as NodeCustomCode, NodeCustomImports as NodeCustomImports, NodeDef as NodeDef, NodeDefInfo as NodeDefInfo, NodeInfo as NodeInfo, NodeState as NodeState, NodeStatus as NodeStatus, NodeTiming as NodeTiming, NodeTypeResponse as NodeTypeResponse, NodeTypes as NodeTypes, NodeUserColumnsResponse as NodeUserColumnsResponse, PrettyResponse as PrettyResponse, PutNodeBlob as PutNodeBlob, QueueMode as QueueMode, QueueStatsResponse as QueueStatsResponse, QueueStatus as QueueStatus, ReadNode as ReadNode, S3Config as S3Config, SetNamedSecret as SetNamedSecret, SettingsObj as SettingsObj, TaskStatus as TaskStatus, Timing as Timing, TimingResult as TimingResult, Timings as Timings, TritonModelsResponse as TritonModelsResponse, URIPrefix as URIPrefix, UUIDResponse as UUIDResponse, UploadFilesResponse as UploadFilesResponse, UserDagDef as UserDagDef, VersionResponse as VersionResponse, WorkerScale as WorkerScale
from .util import ByteResponse as ByteResponse, ServerSideError as ServerSideError, async_compute as async_compute, compute_parallel as compute_parallel, content_to_csv_bytes as content_to_csv_bytes, df_to_csv_bytes as df_to_csv_bytes, get_age as get_age, get_file_hash as get_file_hash, get_file_upload_chunk_size as get_file_upload_chunk_size, get_max_retry as get_max_retry, get_progress_bar as get_progress_bar, get_retry_sleep as get_retry_sleep, has_graph_easy as has_graph_easy, interpret_ctype as interpret_ctype, is_jupyter as is_jupyter, maybe_json_loads as maybe_json_loads, merge_ctype as merge_ctype, safe_opt_num as safe_opt_num, to_bool as to_bool
from _typeshed import Incomplete
from io import BytesIO
from requests import Response as Response
from typing import Any, Callable, IO, Iterable, Iterator, overload
from typing_extensions import Literal

WVD: Incomplete
API_VERSION: int
MIN_API_VERSION: int
DEFAULT_URL: str
DEFAULT_NAMESPACE: str
METHOD_DELETE: str
METHOD_FILE: str
METHOD_GET: str
METHOD_LONGPOST: str
METHOD_POST: str
METHOD_PUT: str
PREFIX: str
INPUT_CSV_EXT: str
INPUT_TSV_EXT: str
INPUT_ZIP_EXT: str
INPUT_EXT: Incomplete
FUNC = Callable[..., Any]
CUSTOM_NODE_TYPES: Incomplete
NO_RETRY: list[str]
CONSUMER_DAG: str
ConsumerType: Incomplete
CONSUMER_ERR: ConsumerType
CONSUMER_ERR_MSG: ConsumerType
CONSUMER_TYPES: set[ConsumerType]

class AccessDenied(Exception): ...

class LegacyVersion(Exception):
    def __init__(self, api_version: int) -> None: ...
    def get_api_version(self) -> int: ...

class KafkaErrorMessageState:
    def __init__(self) -> None: ...
    def get_msg(self, input_id: str) -> str | None: ...
    def add_msg(self, input_id: str, msg: str) -> None: ...
    def get_unmatched(self) -> Iterable[str]: ...
    def add_unmatched(self, msg: str) -> None: ...

class XYMEClient:
    def __init__(self, url: str, token: str | None, namespace: str) -> None: ...
    def get_api_version(self) -> int: ...
    def get_api_version_minor(self) -> int: ...
    def has_version(self, major: int, minor: int) -> bool: ...
    def set_auto_refresh(self, is_auto_refresh: bool) -> None: ...
    def is_auto_refresh(self) -> bool: ...
    def refresh(self) -> None: ...
    def bulk_operation(self) -> Iterator[bool]: ...
    def request_bytes(self, method: str, path: str, args: dict[str, Any], files: dict[str, BytesIO] | None = None, add_prefix: bool = True, add_namespace: bool = True, api_version: int | None = None) -> tuple[BytesIO, str]: ...
    def request_json(self, method: str, path: str, args: dict[str, Any], add_prefix: bool = True, add_namespace: bool = True, files: dict[str, IO[bytes]] | None = None, api_version: int | None = None) -> dict[str, Any]: ...
    def get_server_version(self) -> VersionResponse: ...
    def get_version_override(self) -> dict[str, list[str | None]]: ...
    def get_namespaces(self) -> list[str]: ...
    def get_dags(self) -> list[str]: ...
    def get_dag_ages(self) -> list[dict[str, str | None]]: ...
    def get_dag_times(self, retrieve_times: bool = True) -> tuple[float, list[DagStatus]]: ...
    def get_dag(self, dag_uri: str) -> DagHandle: ...
    def get_blob_handle(self, uri: str, is_full: bool = False) -> BlobHandle: ...
    def get_node_defs(self) -> dict[str, NodeDefInfo]: ...
    def create_new_blob(self, blob_type: str) -> str: ...
    def get_blob_owner(self, blob_uri: str) -> BlobOwner: ...
    def set_blob_owner(self, blob_uri: str, dag_id: str | None = None, node_id: str | None = None, external_owner: bool = False) -> BlobOwner: ...
    def create_new_dag(self, username: str | None = None, dagname: str | None = None, index: int | None = None) -> str: ...
    def get_blob_type(self, blob_uri: str) -> BlobTypeResponse: ...
    def get_csv_blob(self, blob_uri: str) -> CSVBlobHandle: ...
    def get_torch_blob(self, blob_uri: str) -> TorchBlobHandle: ...
    def get_custom_code_blob(self, blob_uri: str) -> CustomCodeBlobHandle: ...
    def get_json_blob(self, blob_uri: str) -> JSONBlobHandle: ...
    def duplicate_dag(self, dag_uri: str, dest_uri: str | None = None, copy_nonowned_blobs: bool | None = None, retain_nonowned_blobs: bool = False, warnings_io: IO[Any] | None = ...) -> str: ...
    def set_dag(self, dag_uri: str, defs: UserDagDef, warnings_io: IO[Any] | None = ...) -> DagHandle: ...
    def set_settings(self, config_token: str, settings: SettingsObj) -> SettingsObj: ...
    def get_settings(self) -> SettingsObj: ...
    def get_allowed_custom_imports(self) -> AllowedCustomImports: ...
    @overload
    def check_queue_stats(self, dag: str | None, minimal: Literal[True]) -> MinimalQueueStatsResponse: ...
    @overload
    def check_queue_stats(self, dag: str | None, minimal: Literal[False]) -> QueueStatsResponse: ...
    @overload
    def check_queue_stats(self, dag: str | None, minimal: bool) -> MinimalQueueStatsResponse | QueueStatsResponse: ...
    def get_instance_status(self, dag_uri: str | None = None, node_id: str | None = None) -> dict[InstanceStatus, int]: ...
    def get_queue_mode(self) -> str: ...
    def set_queue_mode(self, mode: str) -> str: ...
    def flush_all_queue_data(self) -> None: ...
    def get_cache_stats(self) -> CacheStats: ...
    def reset_cache(self) -> CacheStats: ...
    def create_kafka_error_topic(self) -> KafkaTopics: ...
    def get_kafka_error_topic(self) -> str: ...
    def get_kafka_error_message_topic(self) -> str: ...
    def delete_kafka_error_topic(self) -> KafkaTopics: ...
    def read_kafka_errors(self, consumer_type: str, offset: str = 'current') -> list[str]: ...
    def read_kafka_full_json_errors(self, input_id_path: list[str], err_msg_state: KafkaErrorMessageState) -> Iterable[tuple[str, str]]: ...
    def get_named_secrets(self, config_token: str | None = None, show_values: bool = False) -> dict[str, str | None]: ...
    def set_named_secret(self, config_token: str, key: str, value: str) -> bool: ...
    def get_error_logs(self) -> str: ...
    def get_known_blobs(self, blob_type: str | None = None, connector: str | None = None) -> list[str]: ...
    def get_known_blob_ages(self, blob_type: str | None = None, connector: str | None = None) -> list[tuple[str, str]]: ...
    def get_known_blob_times(self, retrieve_times: bool, blob_type: str | None = None, connector: str | None = None) -> tuple[float, list[tuple[str, float | None]]]: ...
    def get_triton_models(self) -> list[str]: ...
    @staticmethod
    def read_dvc(path: str, repo: str, rev: str | None = 'HEAD', warnings_io: IO[Any] | None = ...) -> Any: ...
    @staticmethod
    def get_env_str(key: str, default: str | None = None) -> str: ...
    @staticmethod
    def get_env_int(key: str, default: int | None = None) -> int: ...
    @staticmethod
    def get_env_bool(key: str, default: bool | None = None) -> bool: ...
    @staticmethod
    def load_json(json_path: str) -> dict[str, Any]: ...
    @classmethod
    def load_s3_config(cls, config_path: str) -> S3Config: ...
    @classmethod
    def download_s3_from_file(cls, dest_path: list[str], config_path: str) -> None: ...
    @staticmethod
    def download_s3(dest_path: list[str], config: S3Config) -> None: ...
    @classmethod
    def upload_s3_from_file(cls, source_path: list[str], config_path: str) -> None: ...
    @staticmethod
    def upload_s3(source_path: list[str], config: S3Config) -> None: ...
    def get_uuid(self) -> str: ...
    def delete_blobs(self, blob_uris: list[str]) -> DeleteBlobResponse: ...

class DagHandle:
    def __init__(self, client: XYMEClient, dag_uri: str) -> None: ...
    def refresh(self) -> None: ...
    def get_info(self) -> DagInfo: ...
    def get_nodes(self) -> list[str]: ...
    def get_node(self, node_name: str) -> NodeHandle: ...
    def get_uri(self) -> str: ...
    def get_name(self) -> str: ...
    def get_company(self) -> str: ...
    def get_state_uri(self) -> str: ...
    def get_version_override(self) -> str: ...
    def get_kafka_topics(self) -> tuple[str | None, str | None]: ...
    def get_uri_prefix(self) -> URIPrefix: ...
    def get_timing(self, blacklist: list[str] | None = None) -> TimingResult: ...
    def is_high_priority(self) -> bool: ...
    def is_queue(self) -> bool: ...
    def get_queue_mng(self) -> str | None: ...
    def get_ins(self) -> list[str]: ...
    def get_outs(self) -> list[tuple[str, str]]: ...
    def bulk_operation(self) -> Iterator[bool]: ...
    def set_dag(self, defs: UserDagDef) -> None: ...
    def dynamic_model(self, inputs: list[Any], format_method: str = 'simple', no_cache: bool = False) -> list[Any]: ...
    def dynamic_list(self, inputs: list[Any], input_key: str | None = None, output_key: str | None = None, split_th: int | None = 1000, max_threads: int = 50, format_method: str = 'simple', force_keys: bool = False, no_cache: bool = False) -> list[Any]: ...
    def dynamic(self, input_data: BytesIO) -> ByteResponse | None: ...
    def dynamic_obj(self, input_obj: Any) -> ByteResponse | None: ...
    def dynamic_async(self, input_data: list[BytesIO]) -> list['ComputationHandle']: ...
    def set_dynamic_error_message(self, msg: str | None) -> None: ...
    def get_dynamic_error_message(self) -> str | None: ...
    def dynamic_async_obj(self, input_data: list[Any]) -> list['ComputationHandle']: ...
    def get_dynamic_result(self, value_id: str) -> ByteResponse | None: ...
    def get_dynamic_status(self, value_ids: list['ComputationHandle']) -> dict['ComputationHandle', QueueStatus]: ...
    def get_dynamic_bulk(self, input_data: list[BytesIO], max_buff: int = 4000, block_size: int = 5, num_threads: int = 20) -> Iterable[ByteResponse | None]: ...
    def get_dynamic_bulk_obj(self, input_data: list[Any], max_buff: int = 4000, block_size: int = 5, num_threads: int = 20) -> Iterable[ByteResponse | None]: ...
    def pretty(self, nodes_only: bool = False, allow_unicode: bool = True, method: str | None = 'dot', fields: list[str] | None = None, output_format: str | None = 'png', display: IO[Any] | None = ...) -> str | None: ...
    def pretty_obj(self, nodes_only: bool = False, allow_unicode: bool = True, fields: list[str] | None = None) -> list[DagPrettyNode]: ...
    def get_def(self, full: bool = True) -> UserDagDef: ...
    def set_attr(self, attr: str, value: Any) -> None: ...
    def set_name(self, value: str) -> None: ...
    def set_company(self, value: str) -> None: ...
    def set_state_uri(self, value: str) -> None: ...
    def set_uri_prefix(self, value: URIPrefix) -> None: ...
    def set_high_priority(self, value: bool) -> None: ...
    def set_queue_mng(self, value: str | None) -> None: ...
    def set_version_override(self, value: str | None) -> None: ...
    def set_kafka_input_topic(self, value: str | None) -> None: ...
    def set_kafka_output_topic(self, value: str | None) -> None: ...
    @overload
    def check_queue_stats(self, minimal: Literal[True]) -> MinimalQueueStatsResponse: ...
    @overload
    def check_queue_stats(self, minimal: Literal[False]) -> QueueStatsResponse: ...
    @overload
    def check_queue_stats(self, minimal: bool) -> MinimalQueueStatsResponse | QueueStatsResponse: ...
    def scale_worker(self, replicas: int) -> int: ...
    def reload(self, timestamp: float | None = None) -> float: ...
    def get_kafka_input_topic(self, postfix: str = '') -> str: ...
    def get_kafka_output_topic(self) -> str: ...
    def set_kafka_topic_partitions(self, num_partitions: int, postfix: str = '', large_input_retention: bool = False, no_output: bool = False) -> KafkaTopics: ...
    def post_kafka_objs(self, input_objs: list[Any]) -> list[str]: ...
    def post_kafka_msgs(self, input_data: list[BytesIO], postfix: str = '') -> list[str]: ...
    def read_kafka_output(self, offset: str = 'current', max_rows: int = 100) -> ByteResponse | None: ...
    def get_kafka_offsets(self, alive: bool, postfix: str | None = None) -> KafkaOffsets: ...
    def get_kafka_throughput(self, postfix: str | None = None, segment_interval: float = 120.0, segments: int = 5) -> KafkaThroughput: ...
    def get_kafka_group(self) -> KafkaGroup: ...
    def set_kafka_group(self, group_id: str | None = None, reset: str | None = None, **kwargs: Any) -> KafkaGroup: ...
    def delete(self) -> DeleteBlobResponse: ...
    def download_full_dag_zip(self, to_path: str | None) -> io.BytesIO | None: ...
    def upload_full_dag_zip(self, source: str, max_threads: int = 10) -> list['BlobHandle']: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class NodeHandle:
    def __init__(self, client: XYMEClient, dag: DagHandle, node_id: str, node_name: str, kind: str) -> None: ...
    def as_owner(self) -> BlobOwner: ...
    @staticmethod
    def from_node_info(client: XYMEClient, dag: DagHandle, node_info: NodeInfo, prev: NodeHandle | None) -> NodeHandle: ...
    def update_info(self, node_info: NodeInfo) -> None: ...
    def get_dag(self) -> DagHandle: ...
    def get_id(self) -> str: ...
    def get_name(self) -> str: ...
    def get_type(self) -> str: ...
    def get_node_def(self) -> NodeDefInfo: ...
    def get_inputs(self) -> set[str]: ...
    def get_input(self, key: str) -> tuple['NodeHandle', str]: ...
    def get_status(self) -> TaskStatus: ...
    def has_config_error(self) -> bool: ...
    def get_config_error(self) -> str | None: ...
    def get_version_override(self) -> str | None: ...
    def get_blobs(self) -> list[str]: ...
    def get_blob_handles(self) -> dict[str, 'BlobHandle']: ...
    def get_blob_handle(self, key: str) -> BlobHandle: ...
    def set_blob_uri(self, key: str, blob_uri: str) -> str: ...
    def get_in_cursor_states(self) -> dict[str, int]: ...
    def get_highest_chunk(self) -> int: ...
    def get_short_status(self, allow_unicode: bool = True) -> str: ...
    def get_logs(self) -> str: ...
    def get_timing(self) -> list[Timing]: ...
    def read_blob(self, key: str, chunk: int | None, force_refresh: bool) -> BlobHandle: ...
    def get_index_col(self) -> str: ...
    def get_row_id_col(self) -> str: ...
    def read(self, key: str, chunk: int | None, force_refresh: bool = False, filter_id: bool = True) -> ByteResponse | None: ...
    def read_all(self, key: str, force_refresh: bool = False, filter_id: bool = True) -> ByteResponse | None: ...
    def clear(self) -> NodeState: ...
    def requeue(self) -> NodeState: ...
    def fix_error(self) -> NodeState: ...
    def get_blob_uri(self, blob_key: str, blob_type: str) -> tuple[str, BlobOwner]: ...
    def get_csv_blob(self, key: str = 'orig') -> CSVBlobHandle: ...
    def get_torch_blob(self, key: str = 'orig') -> TorchBlobHandle: ...
    def get_json_blob(self, key: str = 'jsons_in') -> JSONBlobHandle: ...
    def get_custom_code_blob(self, key: str = 'custom_code') -> CustomCodeBlobHandle: ...
    def check_custom_code_node(self) -> None: ...
    def set_custom_imports(self, modules: list[list[str]]) -> NodeCustomImports: ...
    def get_custom_imports(self) -> NodeCustomImports: ...
    def set_es_query(self, query: dict[str, Any]) -> ESQueryResponse: ...
    def get_es_query(self) -> ESQueryResponse: ...
    def get_user_columns(self, key: str) -> NodeUserColumnsResponse: ...
    def get_input_example(self) -> dict[str, ByteResponse | None]: ...
    def get_def(self) -> NodeDef: ...
    def is_model(self) -> bool: ...
    def ensure_is_model(self) -> None: ...
    def setup_model(self, obj: dict[str, Any]) -> ModelInfo: ...
    def get_model_params(self) -> ModelParamsResponse: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

EMPTY_BLOB_PREFIX: str

class BlobHandle:
    def __init__(self, client: XYMEClient, uri: str, is_full: bool) -> None: ...
    def is_full(self) -> bool: ...
    def is_empty(self) -> bool: ...
    def get_uri(self) -> str: ...
    def get_path(self, *path: str) -> BlobHandle: ...
    def get_parent(self) -> BlobHandle: ...
    def get_ctype(self) -> str | None: ...
    def clear_info_cache(self) -> None: ...
    def get_info(self) -> dict[str, Any]: ...
    def get_content(self) -> ByteResponse | None: ...
    def list_files(self) -> list['BlobHandle']: ...
    def as_str(self) -> str: ...
    def set_owner(self, owner: NodeHandle) -> BlobOwner: ...
    def get_owner(self) -> BlobOwner: ...
    def set_local_owner(self, owner: BlobOwner) -> None: ...
    def get_owner_dag(self) -> str | None: ...
    def get_owner_node(self) -> str: ...
    def set_model_threshold(self, threshold: float, pos_label: str) -> ModelInfo: ...
    def del_model_threshold(self) -> ModelInfo: ...
    def get_model_info(self) -> ModelInfo: ...
    def copy_to(self, to_uri: str, new_owner: NodeHandle | None = None, external_owner: bool = False) -> BlobHandle: ...
    def download_zip(self, to_path: str | None) -> io.BytesIO | None: ...
    def upload_zip(self, source: str | io.BytesIO, max_threads: int = 10) -> list['BlobHandle']: ...
    def upload_model_file(self, model_obj: IO[bytes], xcols: list[str] | None, ycols: list[str] | None, is_clf: bool, model_name: str, version: int = -1, model_params: dict[str, Any] | None = None, delete_later_versions: bool = False, max_threads: int = 10, full_init: bool = True) -> UploadFilesResponse: ...
    def upload_sklike_model(self, model: Any, xcols: list[str], ycols: list[str] | None, is_clf: bool, model_name: str | None = None, version: int = -1, model_params: dict[str, Any] | None = None, delete_later_versions: bool = False, full_init: bool = True) -> UploadFilesResponse: ...
    def convert_model(self, version: int | None = None, reload: bool = True) -> ModelReleaseResponse: ...
    def delete(self) -> DeleteBlobResponse: ...
    def get_model_release(self) -> ModelReleaseResponse: ...
    def get_model_version(self) -> ModelVersionResponse: ...
    def copy_model_version(self, read_version: int, write_version: int, overwrite: bool) -> ModelVersionResponse: ...
    def delete_model_version(self, version: int) -> ModelVersionResponse: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class CSVBlobHandle(BlobHandle):
    def finish_csv_upload(self, filename: str | None = None) -> UploadFilesResponse: ...
    def add_from_file(self, filename: str, progress_bar: IO[Any] | None = ..., requeue_on_finish: NodeHandle | None = None, max_threads: int = 10) -> UploadFilesResponse | None: ...
    def add_from_df(self, df: pd.DataFrame, progress_bar: IO[Any] | None = ..., requeue_on_finish: NodeHandle | None = None, max_threads: int = 10) -> UploadFilesResponse | None: ...
    def add_from_content(self, content: bytes | str | pd.DataFrame, progress_bar: IO[Any] | None = ..., requeue_on_finish: NodeHandle | None = None, max_threads: int = 10) -> UploadFilesResponse | None: ...

class TorchBlobHandle(BlobHandle):
    def finish_torch_upload(self, filename: str | None = None) -> UploadFilesResponse: ...
    def add_from_file(self, filename: str, progress_bar: IO[Any] | None = ..., max_threads: int = 10) -> UploadFilesResponse | None: ...

class JSONBlobHandle(BlobHandle):
    def __init__(self, client: XYMEClient, uri: str, is_full: bool) -> None: ...
    def get_count(self) -> int | None: ...
    def append_jsons(self, jsons: list[Any], requeue_on_finish: NodeHandle | None = None) -> None: ...

class CustomCodeBlobHandle(BlobHandle):
    def set_custom_imports(self, modules: list[list[str]]) -> NodeCustomImports: ...
    def get_custom_imports(self) -> NodeCustomImports: ...
    def set_custom_code(self, func: FUNC) -> NodeCustomCode: ...
    def get_custom_code(self) -> NodeCustomCode: ...

class ComputationHandle:
    def __init__(self, dag: DagHandle, value_id: str, get_dyn_error: Callable[[], str | None], set_dyn_error: Callable[[str], None]) -> None: ...
    def has_fetched(self) -> bool: ...
    def get(self) -> ByteResponse | None: ...
    def get_id(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

def default_xyme_client() -> XYMEClient: ...
def create_xyme_client(url: str, token: str | None = None, namespace: str = ...) -> XYMEClient: ...
