# Stubs for pandas.io.msgpack (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,unused-wildcard-import
# pylint: disable=no-name-in-module


from typing import Any
from pandas.io.msgpack.exceptions import *
from pandas.io.msgpack._unpacker import (
    unpack as unpack,
    unpackb as unpackb,
    Unpacker as Unpacker,
)
from pandas.io.msgpack._packer import (
    Packer as Packer,
)


class ExtType:
    def __new__(cls, code: Any, data: Any) -> Any:
        ...



def pack(o: Any, stream: Any, **kwargs: Any) -> None:
    ...


def packb(o: Any, **kwargs: Any) -> Any:
    ...


load = unpack
loads = unpackb
dump = pack
dumps = packb
