# Stubs for pandas.io.msgpack.exceptions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,no-self-use,invalid-name
# pylint: disable=relative-beyond-top-level,line-too-long,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member

from typing import Any

class UnpackException(Exception):
    ...

class BufferFull(UnpackException):
    ...

class OutOfData(UnpackException):
    ...

class UnpackValueError(UnpackException, ValueError):
    ...


class ExtraData(ValueError):
    unpacked: Any = ...
    extra: Any = ...
    def __init__(self, unpacked: Any, extra: Any) -> None:
        ...


class PackException(Exception):
    ...

class PackValueError(PackException, ValueError):
    ...
